-- Seed major countries (Serbia already exists from 003)
INSERT INTO neighborhoods (name, type) VALUES
  ('Afghanistan', 'country'),
  ('Albania', 'country'),
  ('Algeria', 'country'),
  ('Argentina', 'country'),
  ('Armenia', 'country'),
  ('Australia', 'country'),
  ('Austria', 'country'),
  ('Azerbaijan', 'country'),
  ('Bangladesh', 'country'),
  ('Belarus', 'country'),
  ('Belgium', 'country'),
  ('Bolivia', 'country'),
  ('Bosnia and Herzegovina', 'country'),
  ('Brazil', 'country'),
  ('Bulgaria', 'country'),
  ('Cambodia', 'country'),
  ('Cameroon', 'country'),
  ('Canada', 'country'),
  ('Chile', 'country'),
  ('China', 'country'),
  ('Colombia', 'country'),
  ('Costa Rica', 'country'),
  ('Croatia', 'country'),
  ('Cuba', 'country'),
  ('Cyprus', 'country'),
  ('Czech Republic', 'country'),
  ('Denmark', 'country'),
  ('Dominican Republic', 'country'),
  ('Ecuador', 'country'),
  ('Egypt', 'country'),
  ('Estonia', 'country'),
  ('Ethiopia', 'country'),
  ('Finland', 'country'),
  ('France', 'country'),
  ('Georgia', 'country'),
  ('Germany', 'country'),
  ('Ghana', 'country'),
  ('Greece', 'country'),
  ('Guatemala', 'country'),
  ('Hungary', 'country'),
  ('Iceland', 'country'),
  ('India', 'country'),
  ('Indonesia', 'country'),
  ('Iran', 'country'),
  ('Iraq', 'country'),
  ('Ireland', 'country'),
  ('Israel', 'country'),
  ('Italy', 'country'),
  ('Jamaica', 'country'),
  ('Japan', 'country'),
  ('Jordan', 'country'),
  ('Kazakhstan', 'country'),
  ('Kenya', 'country'),
  ('Kosovo', 'country'),
  ('Kuwait', 'country'),
  ('Kyrgyzstan', 'country'),
  ('Latvia', 'country'),
  ('Lebanon', 'country'),
  ('Libya', 'country'),
  ('Lithuania', 'country'),
  ('Luxembourg', 'country'),
  ('Malaysia', 'country'),
  ('Malta', 'country'),
  ('Mexico', 'country'),
  ('Moldova', 'country'),
  ('Mongolia', 'country'),
  ('Montenegro', 'country'),
  ('Morocco', 'country'),
  ('Myanmar', 'country'),
  ('Nepal', 'country'),
  ('Netherlands', 'country'),
  ('New Zealand', 'country'),
  ('Nigeria', 'country'),
  ('North Macedonia', 'country'),
  ('Norway', 'country'),
  ('Oman', 'country'),
  ('Pakistan', 'country'),
  ('Palestine', 'country'),
  ('Panama', 'country'),
  ('Paraguay', 'country'),
  ('Peru', 'country'),
  ('Philippines', 'country'),
  ('Poland', 'country'),
  ('Portugal', 'country'),
  ('Qatar', 'country'),
  ('Romania', 'country'),
  ('Russia', 'country'),
  ('Saudi Arabia', 'country'),
  ('Senegal', 'country'),
  ('Singapore', 'country'),
  ('Slovakia', 'country'),
  ('Slovenia', 'country'),
  ('South Africa', 'country'),
  ('South Korea', 'country'),
  ('Spain', 'country'),
  ('Sri Lanka', 'country'),
  ('Sudan', 'country'),
  ('Sweden', 'country'),
  ('Switzerland', 'country'),
  ('Syria', 'country'),
  ('Taiwan', 'country'),
  ('Tanzania', 'country'),
  ('Thailand', 'country'),
  ('Tunisia', 'country'),
  ('Turkey', 'country'),
  ('Ukraine', 'country'),
  ('United Arab Emirates', 'country'),
  ('United Kingdom', 'country'),
  ('United States', 'country'),
  ('Uruguay', 'country'),
  ('Uzbekistan', 'country'),
  ('Venezuela', 'country'),
  ('Vietnam', 'country');
