-- Seed capital cities for each country (Novi Sad already exists for Serbia)
DO $$
DECLARE
  rec RECORD;
BEGIN
  FOR rec IN
    SELECT * FROM (VALUES
      ('Afghanistan', 'Kabul'),
      ('Albania', 'Tirana'),
      ('Algeria', 'Algiers'),
      ('Argentina', 'Buenos Aires'),
      ('Armenia', 'Yerevan'),
      ('Australia', 'Canberra'),
      ('Austria', 'Vienna'),
      ('Azerbaijan', 'Baku'),
      ('Bangladesh', 'Dhaka'),
      ('Belarus', 'Minsk'),
      ('Belgium', 'Brussels'),
      ('Bolivia', 'La Paz'),
      ('Bosnia and Herzegovina', 'Sarajevo'),
      ('Brazil', 'Brasilia'),
      ('Bulgaria', 'Sofia'),
      ('Cambodia', 'Phnom Penh'),
      ('Cameroon', 'Yaounde'),
      ('Canada', 'Ottawa'),
      ('Chile', 'Santiago'),
      ('China', 'Beijing'),
      ('Colombia', 'Bogota'),
      ('Costa Rica', 'San Jose'),
      ('Croatia', 'Zagreb'),
      ('Cuba', 'Havana'),
      ('Cyprus', 'Nicosia'),
      ('Czech Republic', 'Prague'),
      ('Denmark', 'Copenhagen'),
      ('Dominican Republic', 'Santo Domingo'),
      ('Ecuador', 'Quito'),
      ('Egypt', 'Cairo'),
      ('Estonia', 'Tallinn'),
      ('Ethiopia', 'Addis Ababa'),
      ('Finland', 'Helsinki'),
      ('France', 'Paris'),
      ('Georgia', 'Tbilisi'),
      ('Germany', 'Berlin'),
      ('Ghana', 'Accra'),
      ('Greece', 'Athens'),
      ('Guatemala', 'Guatemala City'),
      ('Hungary', 'Budapest'),
      ('Iceland', 'Reykjavik'),
      ('India', 'New Delhi'),
      ('Indonesia', 'Jakarta'),
      ('Iran', 'Tehran'),
      ('Iraq', 'Baghdad'),
      ('Ireland', 'Dublin'),
      ('Israel', 'Jerusalem'),
      ('Italy', 'Rome'),
      ('Jamaica', 'Kingston'),
      ('Japan', 'Tokyo'),
      ('Jordan', 'Amman'),
      ('Kazakhstan', 'Astana'),
      ('Kenya', 'Nairobi'),
      ('Kosovo', 'Pristina'),
      ('Kuwait', 'Kuwait City'),
      ('Kyrgyzstan', 'Bishkek'),
      ('Latvia', 'Riga'),
      ('Lebanon', 'Beirut'),
      ('Libya', 'Tripoli'),
      ('Lithuania', 'Vilnius'),
      ('Luxembourg', 'Luxembourg City'),
      ('Malaysia', 'Kuala Lumpur'),
      ('Malta', 'Valletta'),
      ('Mexico', 'Mexico City'),
      ('Moldova', 'Chisinau'),
      ('Mongolia', 'Ulaanbaatar'),
      ('Montenegro', 'Podgorica'),
      ('Morocco', 'Rabat'),
      ('Myanmar', 'Naypyidaw'),
      ('Nepal', 'Kathmandu'),
      ('Netherlands', 'Amsterdam'),
      ('New Zealand', 'Wellington'),
      ('Nigeria', 'Abuja'),
      ('North Macedonia', 'Skopje'),
      ('Norway', 'Oslo'),
      ('Oman', 'Muscat'),
      ('Pakistan', 'Islamabad'),
      ('Palestine', 'Ramallah'),
      ('Panama', 'Panama City'),
      ('Paraguay', 'Asuncion'),
      ('Peru', 'Lima'),
      ('Philippines', 'Manila'),
      ('Poland', 'Warsaw'),
      ('Portugal', 'Lisbon'),
      ('Qatar', 'Doha'),
      ('Romania', 'Bucharest'),
      ('Russia', 'Moscow'),
      ('Saudi Arabia', 'Riyadh'),
      ('Senegal', 'Dakar'),
      ('Serbia', 'Belgrade'),
      ('Singapore', 'Singapore'),
      ('Slovakia', 'Bratislava'),
      ('Slovenia', 'Ljubljana'),
      ('South Africa', 'Pretoria'),
      ('South Korea', 'Seoul'),
      ('Spain', 'Madrid'),
      ('Sri Lanka', 'Colombo'),
      ('Sudan', 'Khartoum'),
      ('Sweden', 'Stockholm'),
      ('Switzerland', 'Bern'),
      ('Syria', 'Damascus'),
      ('Taiwan', 'Taipei'),
      ('Tanzania', 'Dodoma'),
      ('Thailand', 'Bangkok'),
      ('Tunisia', 'Tunis'),
      ('Turkey', 'Ankara'),
      ('Ukraine', 'Kyiv'),
      ('United Arab Emirates', 'Abu Dhabi'),
      ('United Kingdom', 'London'),
      ('United States', 'Washington D.C.'),
      ('Uruguay', 'Montevideo'),
      ('Uzbekistan', 'Tashkent'),
      ('Venezuela', 'Caracas'),
      ('Vietnam', 'Hanoi')
    ) AS t(country_name, capital_name)
  LOOP
    INSERT INTO neighborhoods (name, type, parent_id)
    SELECT rec.capital_name, 'city', n.id
    FROM neighborhoods n
    WHERE n.name = rec.country_name AND n.type = 'country';
  END LOOP;
END $$;
